proyecto/estudiantes/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import *

app_name = 'estudiantes'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('create-student', views.CreateStudent.as_view(), name='create-student'),
    path('list-student', views.listStudent, name='list-student'),
    url(r'^edit-student/(?P<pk>\d+)/$', views.EditStudent.as_view(), name="edit-student"),    
    path('delete-student/<int:id>/', views.deleteStudent, name='delete-student'),

]

proyecto/principal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('estudiantes.urls', 'estudiantes'), namespace='estudiantes')),

]

proyecto/estudiantes/models.py
from django.db import models

# Create your models here.

class Estudiante(models.Model):
    nombres = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    carrera = models.CharField(max_length=100)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=10)

    def __str__(self):
        return self.nombres.apellidos

proyecto/estudiantes/forms.py
from django import forms
from .models import *

class EstudianteForm(forms.ModelForm):
    class Meta: 
        model = Estudiante
        fields = [
            'nombres',
            'apellidos',
            'carrera',
            'edad',
            'telefono'
        ]

proyecto/estudiantes/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from .models import *
from .forms import*

# Create your views here.
def homepage(request):
    estudiantes = Estudiante.objects.all()
    contexto = {
        'estudiante':estudiantes
    }
    return render(request, "principal/inicio.html", contexto)

class CreateStudent(CreateView):
    model = Estudiante
    form_class = EstudianteForm
    template_name = 'estudiantes/new-student.html'
    success_url = reverse_lazy('estudiantes:list-student')

def listStudent(request):
    estudiante = Estudiante.objects.all()
    contexto = {
        'estudiante': estudiante
    }
    return render(request, 'estudiantes/list-student.html', contexto)

class EditStudent(UpdateView):
    model = Estudiante
    form_class = EstudianteForm
    template_name  = 'estudiantes/edit-student.html'
    success_url = reverse_lazy('estudiantes:list-student')

def deleteStudent(request, id):
    estudiante = Estudiante.objects.get(id = id)
    estudiante.delete()
    return redirect('estudiantes:list-student')

proyecto/templates/estudiantes/edit-student.html
{% extends "principal/principal.html" %}
{% block content %}
<style>
    form {
        font-family: inherit;
        font-size: 100%;
    }
</style>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn" type="submit">Editar</button>
</form>
{% endblock content %}

proyecto/templates/estudiantes/list-student.html
{% extends "principal/principal.html" %}
{% block content %}
<style>
    table {
        border-collapse: collapse
    }

    th {
        text-align: center;
    }

    td,
    h2 {
        text-align: center;
    }
</style>
<h2>LISTA DE TODOS LOS ESTUDIANTES</h1>
    <table class="striped">
        <thead>
            <tr>

                <th>Nombres</th>

                <th>Apellidos</th>

                <th>Carrera</th>

                <th>Edad</th>

                <th>Teléfono</th>

                <th>Opciones</th>


            </tr>
        </thead>

        <tbody>
            {% for estu in estudiante %}
            <tr>

                <td>{{estu.nombres}}</td>

                <td>{{estu.apellidos}}</td>

                <td>{{estu.carrera}}</td>

                <td>{{estu.edad}}</td>

                <td>{{estu.telefono}}</td>

                <td><a href="{% url 'estudiantes:edit-student' estu.id %}"><button class="btn">EDITAR</button></a>

                    <a href="{% url 'estudiantes:delete-student' estu.id %}"><button class="btn">ELIMINAR</button></a>
                </td>

            </tr>
            {% endfor %}

        </tbody>

    </table>
    <br>
    <a href="{% url 'estudiantes:create-student' %}"><button class="btn">CREAR UN NUEVO ESTUDIANTE</button></a>
    {% endblock %}

proyecto/templates/estudiantes/new-student.html
{% extends "principal/principal.html" %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn" type="submit">Crear</button>
</form>
{% endblock content %}

proyecto/templates/principal/include/navbar.html
<nav>
    <div class="nav-wrapper  teal darken-1">
        <a href="/" class="brand-logo">ISTL</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/">Inicio</a></li>
            <li><a href="{% url 'estudiantes:list-student' %}">Lista Estudiantes</a></li>
        </ul>
    </div>
</nav>

proyecto/templates/principal/inicio.html
{% extends "principal/principal.html" %}
{% block content %}
<style></style>
<div class="row">
    <div class="video-container">
        <iframe width="853" height="480" src="https://www.youtube.com/embed/JM_s3AQGyio" frameborder="0" allowfullscreen></iframe>
      </div>
</div>
{% endblock %}

proyecto/templates/principal/principal.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block css %}
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
        integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
    {% endblock css %}
    <title>INSTITUTO SUPERIOR TECNOLÓGICO LOJA</title>
</head>

<body>
    {% include "principal/include/navbar.html" %}
    <div class="container">
        <br>
        {% block content %}
        {% endblock %}
    </div>

    {% block javascript %}
    {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
        integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

    {% endblock javascript %}

</body>

</html>